SMS_MVCDTO33/SMS_MVCDTO/Models/Entities/SalesManager.cs
using Microsoft.EntityFrameworkCore;
using SMS_MVCDTO.Enums;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace SMS_MVCDTO.Models.Entities
{
    [Index(nameof(Email), IsUnique = true)]
    [Index(nameof(PhoneNumber), IsUnique = true)]
    public class SalesManager : BaseEntity
    {
        public User User { get; set; }
        [ForeignKey("User")]
        public string UserId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        [Required]
        [Key]
        public string StaffId { get; set; }
        [Required]
        public string Email { get; set; }
        [Required]
        public string PhoneNumber { get; set; }
        public string HomeAddress { get; set; }
        public string ResidentialAddress { get; set; }
        public bool IsActive { get; set; }
        public DateTime DateOfBirth { get; set; }
        public GenderType Gender { get; set; }
        public MaritalStatusType MaritalStatus { get; set; }
        public UserRoleType userRole { get; set; }
        public string BankAccountNumber { get; set; }
        public string BankName { get; set; }
        public string GuarantorName { get; set; }
        public string GuarantorPhoneNumber { get; set; }
        //public IList<Transaction> Transactions { get; set; }
        //public Wallet Wallets { get; set; }
        /*
         parent,upload photo, upload proof of residence, valid id card
         */
    }
}

SMS_MVCDTO33/SMS_MVCDTO/Controllers/ProductController.cs
using Microsoft.AspNetCore.Mvc;
using SMS_MVCDTO.Interfaces.Services;
using SMS_MVCDTO.Models.ViewModels;

namespace SMS_MVCDTO.Controllers
{
    public class ProductController : Controller
    {
        private readonly IProductService _product;
        private readonly IProductCategoryService _category;
        public ProductController(IProductService product, IProductCategoryService category)
        {
            _product = product;
            _category = category;
        }

        public IActionResult Index()
        {
            var product = _product.GetAll();
            return View(product);
        }

        public IActionResult BelowReorderLevel()
        {
            var product = _product.BelowReorderLevel();
            return View(product);
        }

        public IActionResult Dashboard()
        {
            var product = _product.GetAll();
            return View(product);
        }

        public IActionResult Create()
        {
            var categories = _category.GetAll().ToList();
            var viewModel = new NewProductViewModel
            {
                PCategory = categories
            };
            return View(viewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(NewProductViewModel product)
        {

            if (product != null)
            {
                var existByName = _product.GetById(product.CreateProduct.Barcode);
                if (existByName == null)
                {
                    _product.Create(product.CreateProduct);
                    TempData["success"] = "Created Successfully.";
                    //return RedirectToAction("Index");
                    return RedirectToAction("Dashboard", "Attendant");
                }
                TempData["failed"] = "already exist.";
                return View();
            }

            TempData["failed"] = "failed.";
            return View(product);

        }

        public IActionResult Edit(string barCode)
        {

            var product = _product.GetById(barCode);
            if (product == null)
            {
                return NotFound();
            }
            var categories = _category.GetAll().ToList();
            var viewModel = new NewProductViewModel
            {
                UpdateProduct = product,
                PCategory = categories,
            };
            return View(viewModel);

        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(NewProductViewModel product)
        {
            if (product != null)
            {
                _product.Update(product.UpdateProduct);
                TempData["success"] = "product updated Successfully.";
                return RedirectToAction(nameof(Index));
            }
            TempData["failed"] = "failed.";
            return View(product);
        }


        public IActionResult DeletePreview(string barCode)
        {
            if (barCode != null)
            {
                var product = _product.GetById(barCode);
                if (product != null)
                {
                    return View(product);
                }
                return NotFound();
            }

            return NotFound();
        }

        public IActionResult Delete(string barCode)
        {
            if (barCode != null)
            {
                _product.Delete(barCode);
                return RedirectToAction(nameof(Index));
            }
            return NotFound();
        }

        public IActionResult Details(string barCode)
        {
            if (barCode != null)
            {
                var product = _product.GetById(barCode);
                if (product != null)
                {
                    return View(product);
                }
                return NotFound();
            }
            return NotFound();
        }

        public IActionResult GetById(string barCode)
        {
            if (barCode != null)
            {
                var product = _product.GetById(barCode);
                if (product != null)
                {
                    return View(product);
                }
                return NotFound();
            }
            return NotFound();
        }

        public IActionResult GetByName(string name)
        {
            if (name != null)
            {
                var product = _product.GetByName(name);
                if (product != null)
                {
                    return View(product);
                }
                return NotFound();
            }
            return NotFound();
        }
    }
}

SMS_MVCDTO33/SMS_MVCDTO/Controllers/SalesManagerController.cs
using Microsoft.AspNetCore.Mvc;
using SMS_MVCDTO.Interfaces.Services;
using SMS_MVCDTO.Models.DTOs.SalesManagerDTOs;

namespace SMS_MVCDTO.Controllers
{
    public class SalesManagerController : Controller
    {
        private readonly ISalesManagerService _saleManager;
        public SalesManagerController(ISalesManagerService saleManager)
        {
            _saleManager = saleManager;
        }

        public IActionResult Index()
        {
            //ViewBag.ShowElement1 = true;
            var saleManager = _saleManager.GetSalesManagers();
            return View(saleManager);
        }

        public IActionResult Dashboard()
        {
            //ViewBag.ShowElement1 = true;
            var saleManager = _saleManager.GetSalesManagers();
            return View(saleManager);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(CreateSalesManagerRequestModel createSaleManager)
        {
            if (createSaleManager != null)
            {
                var existByEmail = _saleManager.GetByEmail(createSaleManager.Email);
                if (existByEmail == null)
                {
                    _saleManager.Create(createSaleManager);
                    TempData["success"] = "Registration Successful.    ";
                    return RedirectToAction("Index");
                }
                TempData["failed"] = "Email already Exist.";
                return View();
            }
            else
            {
                TempData["failed"] = "Incomplete details, Registration Failed";
                return View();
            }
        }

        public IActionResult Edit(string staffId)
        {
            var saleManager = _saleManager.GetById(staffId);
            if (saleManager == null)
            {
                return NotFound();
            }
            return View(saleManager);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(SalesManagerResponseModel updateSaleManager)
        {

            _saleManager.Update(updateSaleManager);
            TempData["success"] = "Profile Updated Successfully.";
            return RedirectToAction(nameof(Index));
        }

        public IActionResult DeletePreview(string staffId)
        {
            if (staffId != null)
            {
                var saleManager = _saleManager.GetById(staffId);

                if (saleManager != null)
                {
                    return View(saleManager);
                }
                return NotFound();
            }

            return NotFound();
        }

        //[ValidateAntiForgeryToken]
        //[HttpPost, ActionName("Delete")]
        public IActionResult Delete(string staffId)
        {
            if (staffId != null)
            {
                _saleManager.Delete(staffId);
                return RedirectToAction(nameof(Index));
            }
            return NotFound();
        }

        public IActionResult Details(string staffId)
        {
            if (staffId != null)
            {
                var saleManager = _saleManager.GetById(staffId);

                if (saleManager != null)
                {
                    return View(saleManager);
                }
                return NotFound();
            }

            return NotFound();
        }
    }
}

SMS_MVCDTO33/SMS_MVCDTO/Controllers/TransactionController.cs
using Microsoft.AspNetCore.Mvc;
using SMS_MVCDTO.Interfaces.Services;
using SMS_MVCDTO.Models.DTOs.TransactionDTOs;
using SMS_MVCDTO.Models.ViewModels;

namespace SMS_MVCDTO.Controllers
{
    public class TransactionController : Controller
    {
        private readonly ITransactionService _transaction;
        private readonly IProductService _product;
        public TransactionController(ITransactionService transaction, IProductService product)
        {
            _transaction = transaction;
            _product = product;
        }

        public IActionResult Index(int id)
        {
            if (id != 0)
            {
                var transactions = _transaction.GetAll();
                return View(transactions);
            }
            else
            {
                var transactions = _transaction.GetAllOrderByDate();
                return View(transactions);
            }

        }


        public IActionResult Dashboard()
        {
            var transactions = _transaction.GetAll();
            return View(transactions);
        }


        public IActionResult Create(string barCode)
        {
            var product = _product.GetById(barCode);

            if (product == null)
            {
                return NotFound();
            }

            var productTransact = new CreateProductTransactionViewModel
            {
                Product = product,

            };

            return View(productTransact);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(CreateProductTransactionViewModel productTransaction)
        {

            var transaction = productTransaction.Transaction;

            if (transaction != null)
            {
                transaction.BarCode = productTransaction.Product.Data.Barcode;
                _transaction.Create(transaction);
                TempData["success"] = "Created Successfully.";
                return RedirectToAction("Index");
            }
            TempData["failed"] = "failed.";
            return View();
        }

        public IActionResult DeletePreview(string referenceNo)
        {
            if (referenceNo != null)
            {
                var transaction = _transaction.GetById(referenceNo);
                if (transaction != null)
                {
                    return View(transaction);
                }
                return NotFound();
            }

            return NotFound();
        }

        public IActionResult Delete(string referenceNo)
        {
            if (referenceNo != null)
            {
                _transaction.Delete(referenceNo);
                return RedirectToAction(nameof(Index));
            }
            return NotFound();
        }

        public IActionResult Details(string referenceNo)
        {
            if (referenceNo != null)
            {
                var transaction = _transaction.GetById(referenceNo);
                if (transaction != null)
                {
                    return View(transaction);
                }
                return NotFound();
            }
            return NotFound();
        }

        public IActionResult GetByName(string name)
        {
            if (name != null)
            {
                var transaction = _transaction.GetTransactionByCustomerName(name);
                if (transaction != null)
                {
                    return View(transaction);
                }
                return NotFound();
            }
            return NotFound();
        }

        public IActionResult GetByAttendant(string staffId)
        {
            if (staffId != null)
            {
                var transaction = _transaction.GetByStaffId(staffId);
                if (transaction != null)
                {
                    return View(transaction);
                }
                return NotFound();
            }
            return NotFound();
        }
    }


}

SMS_MVCDTO33/SMS_MVCDTO/Views/SalesManager/Create.cshtml
@using SMS_MVCDTO.Enums
@model SMS_MVCDTO.Models.DTOs.SalesManagerDTOs.CreateSalesManagerRequestModel

@{
	ViewData["Title"] = "Create";
	if (TempData["Success"] != null)
	{
		<h2>@TempData["success"]</h2>
	}
	if (TempData["failed"] != null)
	{
		<h2>@TempData["failed"]</h2>
	}
}
@{
	<h1>Create</h1>

	<h4>Sales Manager</h4>
	<hr />
	<div class="row">
		<div class="col-md-4">
			<form asp-action="Create">
				
				<div class="form-group">
					<label asp-for="FirstName" class="control-label"></label>
					<input asp-for="FirstName" class="form-control" />
					<span asp-validation-for="FirstName" class="text-danger"></span>
				</div>
				<div class="form-group">
					<label asp-for="LastName" class="control-label"></label>
					<input asp-for="LastName" class="form-control" />
					<span asp-validation-for="LastName" class="text-danger"></span>
				</div>

				
				<div class="form-group">
					<label asp-for="Email" class="control-label"></label>
					<input asp-for="Email" class="form-control" />
					<span asp-validation-for="Email" class="text-danger"></span>
				</div>

				<div class="form-group">
					<label asp-for="PhoneNumber" class="control-label"></label>
					<input asp-for="PhoneNumber" class="form-control" />
					<span asp-validation-for="PhoneNumber" class="text-danger"></span>
				</div>
				<div class="form-group">
					<label asp-for="HomeAddress" class="control-label"></label>
					<input asp-for="HomeAddress" class="form-control" />
					<span asp-validation-for="HomeAddress" class="text-danger"></span>
				</div>
				<div class="form-group">
					<label asp-for="ResidentialAddress" class="control-label"></label>
					<input asp-for="ResidentialAddress" class="form-control" />
					<span asp-validation-for="ResidentialAddress" class="text-danger"></span>
				</div>

				
				<div class="form-group">
					<label asp-for="DateOfBirth" class="control-label"></label>
					<input asp-for="DateOfBirth" class="form-control" />
					<span asp-validation-for="DateOfBirth" class="text-danger"></span>
				</div>





				<div class="form-group">
					<label asp-for="Gender" class="control-label" for="Gender"></label>
					<select asp-for="Gender" asp-items="Html.GetEnumSelectList<GenderType>()"></select>
					<span asp-validation-for="Gender" class="text-danger"></span>
				</div>

			


				<div class="form-group">
					<label asp-for="MaritalStatus" class="control-label" for="MaritalStatus"></label>
					<select asp-for="MaritalStatus" asp-items="Html.GetEnumSelectList<MaritalStatusType>()"></select>
					<span asp-validation-for="Gender" class="text-danger"></span>
				</div>


				<div class="form-group">
					<label asp-for="BankAccountNumber" class="control-label"></label>
					<input asp-for="BankAccountNumber" class="form-control" />
					<span asp-validation-for="BankAccountNumber" class="text-danger"></span>
				</div>
				<div class="form-group">
					<label asp-for="BankName" class="control-label"></label>
					<input asp-for="BankName" class="form-control" />
					<span asp-validation-for="BankName" class="text-danger"></span>
				</div>

				<div class="form-group">
					<label asp-for="GuarantorName" class="control-label"></label>
					<input asp-for="GuarantorName" class="form-control" />
					<span asp-validation-for="GuarantorName" class="text-danger"></span>
				</div>

				<div class="form-group">
					<label asp-for="GuarantorPhoneNumber" class="control-label"></label>
					<input asp-for="GuarantorPhoneNumber" class="form-control" />
					<span asp-validation-for="GuarantorPhoneNumber" class="text-danger"></span>
				</div>



				<div class="form-group">
					<label asp-for="Password" class="control-label"></label>
					<input asp-for="Password" type="password" class="form-control" />
					<span asp-validation-for="Password" class="text-danger"></span>
				</div>

				
				<div class="form-group">
					<input type="submit" value="Create" class="btn btn-success" />
				</div>
			</form>
		</div>
	</div>

	<div>
		<a asp-action="Index" class="btn btn-warning">Back to List</a>
	</div>

	<br />
	<br />
	<br />
	<br />
}
@section Scripts {
	@{
		await Html.RenderPartialAsync("_ValidationScriptsPartial");
	}
	}

SMS_MVCDTO33/SMS_MVCDTO/Views/SalesManager/Dashboard.cshtml
@model IEnumerable<SMS_MVCDTO.Models.DTOs.SalesManagerDTOs.SalesManagerResponseModel>

@{
    ViewData["Title"] = "Sales Manager Dashboard";
}
@{

    if (TempData["Success"] != null)
    {
        <h2>@TempData["success"]</h2>
    }
    if (TempData["failed"] != null)
    {
        <h2>@TempData["failed"]</h2>
    }
}





<main class="main">
    <!-- <div class="dashboard"> -->
    <div class="form-container">

        <!-- Signup Form -->
        <h1>Super Admin Dashboard</h1>


        <div id="">



            <p>
                <a asp-action="Create">Create New</a>
            </p>

            <table class="table table-info">
                <thead>
                    <tr>
                        <th>
                            @Html.DisplayNameFor(model => model.Data.StaffId)
                        </th>

                        <th>
                            @Html.DisplayNameFor(model => model.Data.FirstName)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.Data.LastName)
                        </th>

                        <th>
                            @Html.DisplayNameFor(model => model.Data.Email)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.Data.PhoneNumber)
                        </th>

                        <th></th>
                    </tr>
                </thead>
                <tbody>

                    @foreach (var item in Model)
                    {
                        <tr>

                            <td>
                                @Html.DisplayFor(modelItem => item.Data.StaffId)
                            </td>

                            <td>
                                @Html.DisplayFor(modelItem => item.Data.FirstName)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Data.LastName)
                            </td>

                            <td>
                                @Html.DisplayFor(modelItem => item.Data.Email)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Data.PhoneNumber)
                            </td>


                            <td>
                                <a asp-action="Edit" asp-route-staffId="@item.Data.StaffId">Edit</a> |
                                <a asp-action="Details" asp-route-staffId="@item.Data.StaffId">Details</a> |
                                <a asp-action="DeletePreview" asp-route-staffId="@item.Data.StaffId">Delete</a>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>





        </div>

    </div>

    <!-- search box  -->
    <div class="search-container-side">

        <!-- search box  -->
        <div class="search-container">
            <form asp-controller="SalesManager" asp-action="Details">
                <input type="text" placeholder="Staff Id..." name="staffId">
                <button type="submit">
                    <i class="fa fa-search"></i> Search
                </button>
            </form>
        </div>

        <!-- search box  -->
        <div class="search-container">
            <form>
                <input type="text" placeholder="Search1...">
                <button type="submit">
                    <i class="fa fa-search"></i> Search
                </button>
            </form>
        </div>

    </div>


</main>

SMS_MVCDTO33/SMS_MVCDTO/Views/SalesManager/Delete.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

SMS_MVCDTO33/SMS_MVCDTO/Views/SalesManager/DeletePreview.cshtml
@model SMS_MVCDTO.Models.DTOs.SalesManagerDTOs.SalesManagerResponseModel

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Sales Manager</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">

        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Data.FirstName)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Data.FirstName)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Data.LastName)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Data.LastName)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Data.StaffId)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Data.StaffId)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Data.Email)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Data.Email)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Data.PhoneNumber)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Data.PhoneNumber)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Data.HomeAddress)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Data.HomeAddress)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Data.ResidentialAddress)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Data.ResidentialAddress)
        </dd>

        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Data.DateOfBirth)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Data.DateOfBirth)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Data.Gender)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Data.Gender)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Data.MaritalStatus)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Data.MaritalStatus)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Data.userRole)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Data.userRole)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Data.BankAccountNumber)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Data.BankAccountNumber)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Data.BankName)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Data.BankName)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Data.GuarantorName)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Data.GuarantorName)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Data.GuarantorPhoneNumber)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Data.GuarantorPhoneNumber)
        </dd>

    </dl>
</div>

<div>
    <a asp-action="Delete" asp-route-staffId="@Model.Data.StaffId" class="btn btn-danger">Delete</a>
    <a asp-action="Index" class="btn btn-warning">Back to List</a>
</div>

SMS_MVCDTO33/SMS_MVCDTO/Views/SalesManager/Edit.cshtml
@using SMS_MVCDTO.Enums
@model SMS_MVCDTO.Models.DTOs.SalesManagerDTOs.SalesManagerResponseModel

@{
    ViewData["Title"] = "Edit";
    if (TempData["Success"] != null)
    {
        <h2>@TempData["success"]</h2>
    }
}


<h1>Sales Manager Profile Update.</h1>

<h4>Sales Manager</h4>
<hr />

<div asp-controller="SalesManager" asp-action="Edit" style="font-size: 130%;">
    <div class="row">
        <div class="col-md-4">
            <form asp-action="Edit">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <input type="hidden" asp-for="Data.StaffId" />

                <div class="form-group">
                    <label asp-for="Data.FirstName" class="control-label"></label>
                    <input asp-for="Data.FirstName" class="form-control" />
                    <span asp-validation-for="Data.FirstName" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <label asp-for="Data.LastName" class="control-label"></label>
                    <input asp-for="Data.LastName" class="form-control" />
                    <span asp-validation-for="Data.LastName" class="text-danger"></span>
                </div>


                <div class="form-group">
                    <label asp-for="Data.ResidentialAddress" class="control-label"></label>
                    <input asp-for="Data.ResidentialAddress" class="form-control" />
                    <span asp-validation-for="Data.ResidentialAddress" class="text-danger"></span>
                </div>


                <div class="form-group">
                    <label asp-for="Data.MaritalStatus" class="control-label"></label>
                    <select asp-for="Data.MaritalStatus" asp-items="Html.GetEnumSelectList<MaritalStatusType>()"></select>

                    <span asp-validation-for="Data.MaritalStatus" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Data.BankAccountNumber" class="control-label"></label>
                    <input asp-for="Data.BankAccountNumber" class="form-control" />
                    <span asp-validation-for="Data.BankAccountNumber" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Data.BankName" class="control-label"></label>
                    <input asp-for="Data.BankName" class="form-control" />
                    <span asp-validation-for="Data.BankName" class="text-danger"></span>
                </div>


                <div class="form-group">
                    <input type="submit" value="Save" class="btn btn-success" />
                </div>
            </form>
        </div>
    </div>
</div>
<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
    }

SMS_MVCDTO33/SMS_MVCDTO/Views/SalesManager/Index.cshtml
@model IEnumerable<SMS_MVCDTO.Models.DTOs.SalesManagerDTOs.SalesManagerResponseModel>

@{
    ViewData["Title"] = "Home || Sales Manager ";
}
@{
    if (TempData["Success"] != null)
    {
        <h2>@TempData["success"]</h2>
    }
    if (TempData["failed"] != null)
    {
        <h2>@TempData["failed"]</h2>
    }
}


<h1>Sales manager Dashboard</h1>


<div class="dropdown">
    <button class="dropbtn"> Manage Attendant</button>
    <div class="dropdown-menu">
        <a asp-controller="Attendant" asp-action="Dashboard"> Dashboard </a>
        <br />
        <a asp-controller="Attendant" asp-action="Create">Add new attendant</a>
        <br />

    </div>
</div>

<div class="dropdown">
    <button class="dropbtn"> Manage Product</button>
    <div class="dropdown-menu">
        <a asp-controller="Product" asp-action="Dashboard"> Dashboard</a>
        <br />
        <a asp-controller="Product" asp-action="Create">Add new product</a>
        <br />
        @* <a asp-controller="Product" asp-action="Index">Manage all products</a>
        <br />*@
    </div>
</div>
<a asp-controller="Transaction" asp-action="Dashboard">Manage Transactions</a>
<br />
<a asp-controller="Product" asp-action="Dashboard">Manage Inventory</a>
<br />
<br />
<br />