SMS_MVCDTO33/SMS_MVCDTO/Controllers/CustomerController.cs
using Microsoft.AspNetCore.Mvc;
using SMS_MVCDTO.Interfaces.Services;
using SMS_MVCDTO.Models.DTOs.CustomerDTOs;

namespace SMS_MVCDTO.Controllers
{
    public class CustomerController : Controller
    {
        private readonly ICustomerService _customer;
        public CustomerController(ICustomerService customer)
        {
            _customer = customer;
        }

        public IActionResult Index()
        {
            var customers = _customer.GetCustomers();
            return View(customers);
        }

        public IActionResult Dashboard()
        {
            var customers = _customer.GetCustomers();
            return View(customers);
        }

        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(CreateCustomerRequestModel createCustomer)
        {
            if (createCustomer != null)
            {
                var existByEmail = _customer.GetByEmail(createCustomer.Email);
                if (existByEmail == null)
                {
                    _customer.Create(createCustomer);
                    TempData["success"] = "Customer Created Successfully.";
                    return RedirectToAction("Index");
                }
                TempData["failed"] = "Email already exist.";
                return View();
            }
            TempData["failed"] = "Registration failed because of incomplete details.";
            return View();
        }

        public IActionResult Edit(string staffId)
        {
            var customer = _customer.GetById(staffId);
            if (customer == null)
            {
                return NotFound();
            }
            return View(customer);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(CustomerResponseModel editCustomer)
        {
            _customer.Update(editCustomer);
            TempData["success"] = "profile updated Successfully.";
            return RedirectToAction(nameof(Index));
        }

        public IActionResult DeletePreview(string staffId)
        {
            if (staffId != null)
            {
                var customer = _customer.GetById(staffId);
                if (customer != null)
                {
                    return View(customer);
                }
                return NotFound();
            }

            return NotFound();
        }

        public IActionResult Delete(string staffId)
        {
            if (staffId != null)
            {
                _customer.Delete(staffId);
                return RedirectToAction(nameof(Index));
            }
            return NotFound();
        }

        public IActionResult Details(string staffId)
        {
            if (staffId != null)
            {
                var customer = _customer.GetById(staffId);
                if (customer != null)
                {
                    return View(customer);
                }
                return NotFound();
            }
            return NotFound();
        }
    }
}

SMS_MVCDTO33/SMS_MVCDTO/Controllers/ProductController.cs
using Microsoft.AspNetCore.Mvc;
using SMS_MVCDTO.Interfaces.Services;
using SMS_MVCDTO.Models.ViewModels;

namespace SMS_MVCDTO.Controllers
{
    public class ProductController : Controller
    {
        private readonly IProductService _product;
        private readonly IProductCategoryService _category;
        public ProductController(IProductService product, IProductCategoryService category)
        {
            _product = product;
            _category = category;
        }

        public IActionResult Index()
        {
            var product = _product.GetAll();
            return View(product);
        }

        public IActionResult BelowReorderLevel()
        {
            var product = _product.BelowReorderLevel();
            return View(product);
        }

        public IActionResult Dashboard()
        {
            var product = _product.GetAll();
            return View(product);
        }

        public IActionResult Create()
        {
            var categories = _category.GetAll().ToList();
            var viewModel = new NewProductViewModel
            {
                PCategory = categories
            };
            return View(viewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(NewProductViewModel product)
        {

            if (product != null)
            {
                var existByName = _product.GetById(product.CreateProduct.Barcode);
                if (existByName == null)
                {
                    _product.Create(product.CreateProduct);
                    TempData["success"] = "Created Successfully.";
                    //return RedirectToAction("Index");
                    return RedirectToAction("Dashboard", "Attendant");
                }
                TempData["failed"] = "already exist.";
                return View();
            }

            TempData["failed"] = "failed.";
            return View(product);

        }

        public IActionResult Edit(string barCode)
        {

            var product = _product.GetById(barCode);
            if (product == null)
            {
                return NotFound();
            }
            var categories = _category.GetAll().ToList();
            var viewModel = new NewProductViewModel
            {
                UpdateProduct = product,
                PCategory = categories,
            };
            return View(viewModel);

        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(NewProductViewModel product)
        {
            if (product != null)
            {
                _product.Update(product.UpdateProduct);
                TempData["success"] = "product updated Successfully.";
                return RedirectToAction(nameof(Index));
            }
            TempData["failed"] = "failed.";
            return View(product);
        }


        public IActionResult DeletePreview(string barCode)
        {
            if (barCode != null)
            {
                var product = _product.GetById(barCode);
                if (product != null)
                {
                    return View(product);
                }
                return NotFound();
            }

            return NotFound();
        }

        public IActionResult Delete(string barCode)
        {
            if (barCode != null)
            {
                _product.Delete(barCode);
                return RedirectToAction(nameof(Index));
            }
            return NotFound();
        }

        public IActionResult Details(string barCode)
        {
            if (barCode != null)
            {
                var product = _product.GetById(barCode);
                if (product != null)
                {
                    return View(product);
                }
                return NotFound();
            }
            return NotFound();
        }

        public IActionResult GetById(string barCode)
        {
            if (barCode != null)
            {
                var product = _product.GetById(barCode);
                if (product != null)
                {
                    return View(product);
                }
                return NotFound();
            }
            return NotFound();
        }

        public IActionResult GetByName(string name)
        {
            if (name != null)
            {
                var product = _product.GetByName(name);
                if (product != null)
                {
                    return View(product);
                }
                return NotFound();
            }
            return NotFound();
        }
    }
}

SMS_MVCDTO33/SMS_MVCDTO/Controllers/TransactionController.cs
using Microsoft.AspNetCore.Mvc;
using SMS_MVCDTO.Interfaces.Services;
using SMS_MVCDTO.Models.DTOs.TransactionDTOs;
using SMS_MVCDTO.Models.ViewModels;

namespace SMS_MVCDTO.Controllers
{
    public class TransactionController : Controller
    {
        private readonly ITransactionService _transaction;
        private readonly IProductService _product;
        public TransactionController(ITransactionService transaction, IProductService product)
        {
            _transaction = transaction;
            _product = product;
        }

        public IActionResult Index(int id)
        {
            if (id != 0)
            {
                var transactions = _transaction.GetAll();
                return View(transactions);
            }
            else
            {
                var transactions = _transaction.GetAllOrderByDate();
                return View(transactions);
            }

        }


        public IActionResult Dashboard()
        {
            var transactions = _transaction.GetAll();
            return View(transactions);
        }


        public IActionResult Create(string barCode)
        {
            var product = _product.GetById(barCode);

            if (product == null)
            {
                return NotFound();
            }

            var productTransact = new CreateProductTransactionViewModel
            {
                Product = product,

            };

            return View(productTransact);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(CreateProductTransactionViewModel productTransaction)
        {

            var transaction = productTransaction.Transaction;

            if (transaction != null)
            {
                transaction.BarCode = productTransaction.Product.Data.Barcode;
                _transaction.Create(transaction);
                TempData["success"] = "Created Successfully.";
                return RedirectToAction("Index");
            }
            TempData["failed"] = "failed.";
            return View();
        }

        public IActionResult DeletePreview(string referenceNo)
        {
            if (referenceNo != null)
            {
                var transaction = _transaction.GetById(referenceNo);
                if (transaction != null)
                {
                    return View(transaction);
                }
                return NotFound();
            }

            return NotFound();
        }

        public IActionResult Delete(string referenceNo)
        {
            if (referenceNo != null)
            {
                _transaction.Delete(referenceNo);
                return RedirectToAction(nameof(Index));
            }
            return NotFound();
        }

        public IActionResult Details(string referenceNo)
        {
            if (referenceNo != null)
            {
                var transaction = _transaction.GetById(referenceNo);
                if (transaction != null)
                {
                    return View(transaction);
                }
                return NotFound();
            }
            return NotFound();
        }

        public IActionResult GetByName(string name)
        {
            if (name != null)
            {
                var transaction = _transaction.GetTransactionByCustomerName(name);
                if (transaction != null)
                {
                    return View(transaction);
                }
                return NotFound();
            }
            return NotFound();
        }

        public IActionResult GetByAttendant(string staffId)
        {
            if (staffId != null)
            {
                var transaction = _transaction.GetByStaffId(staffId);
                if (transaction != null)
                {
                    return View(transaction);
                }
                return NotFound();
            }
            return NotFound();
        }
    }


}

SMS_MVCDTO33/SMS_MVCDTO/Views/Shared/_Layout.cshtml
@using System.Security.Claims;
@using SMS_MVCDTO.Enums;
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SMS_MVCDTO</title>
    <link rel="stylesheet" href="~/css/FontAwesome6.2/css/all.css">
    <script src="~/js/site.js"></script>

    <!-- <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.14.0/css/all.css" integrity="sha384-HzLeBuhoNPvSl5KYnjx0BT+WB0QEEqLprO+NBkkk5gbc67FTaL7XIGa2w1L0Xbgc" crossorigin="anonymous"> -->
    <link rel="stylesheet" href="~/css/styles.css">
    <link rel="stylesheet" href="~/SMS_MVCDTO.styles.css"
          asp-append-version="true" />

</head>

<body>



   

    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm
                navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area=""
                   asp-controller="Home"
                   asp-action="Index">Colon Sales Record</a>
                @* MDelete *@
                <button class="navbar-toggler" type="button"
                        data-bs-toggle="collapse"
                        data-bs-target=".navbar-collapse"
                        aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle
                        navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                @* MDelete *@

                <div class="navbar-collapse collapse d-sm-inline-flex
                        justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area=""
                               asp-controller="Home"
                               asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area=""
                               asp-controller="Home"
                               asp-action="Privacy">
                                About
                                us
                            </a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area=""
                               asp-controller="Home"
                               asp-action="Privacy">
                                Contact
                                us
                            </a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area=""
                               asp-controller="Home"
                               asp-action="Privacy">Privacy</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area=""
                               asp-controller="Home"
                               asp-action="Privacy">News</a>
                        </li>

                    </ul>


                    <ul class="navbar-nav">


                        @if (User?.FindFirst(ClaimTypes.NameIdentifier) == null)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area=""
                               asp-controller="Home"
                               asp-action="Login">Login</a>
                            </li>
                        }

                        @if (User?.FindFirst(ClaimTypes.NameIdentifier) != null)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area=""
                               asp-controller="Home"
                               asp-action="Logout">Logout</a>
                            </li>
                        }

                        @if (User?.FindFirst(ClaimTypes.NameIdentifier) == null)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area=""
                               asp-controller="Customer"
                               asp-action="Create">Sign-Up</a>
                            </li>
                        }

                    </ul>

                </div>
            </div>
        </nav>
    </header>

    @* <div class="wrapper"> *@


    <div class="bodycontain bd-oline">

        @if (User?.FindFirst(ClaimTypes.NameIdentifier) != null)
        {

            <div class="sidebar ">
                <h3>Navigation</h3>
                <ul>

                    <li><a asp-area="" asp-controller="" asp-action="">Home</a></li>
                    @* <li><a href="#"></a></li> *@

                    <li class="dropdown">
                        <a href="#">Attendants</a>
                        <ul class="dropdown-content">
                            <li>
                                <a asp-area="" asp-controller="Attendant"
                               asp-action="Create">Create Attendants</a>
                            </li>
                            <li>
                                <a asp-area="" asp-controller="Attendant"
                               asp-action="Dashboard">Manage Attendants</a>
                            </li>
                            <li>
                                <a asp-area="" asp-controller="Attendant"
                               asp-action="">View all attendants</a>
                            </li>
                        </ul>
                    </li>

                    @if (User?.FindFirst(ClaimTypes.Role) != null)
                    {
                        @if (User.FindFirst(ClaimTypes.Role).Value == UserRoleType.SuperAdmin.ToString())
                        {
                            <li class="dropdown">
                                <a href="#">Customers</a>
                                <ul class="dropdown-content">
                                    <li>
                                        <a asp-area="" asp-controller="Customer"
                               asp-action="Create">Create Customer</a>
                                    </li>
                                    <li>
                                        <a asp-area="" asp-controller="Customer"
                               asp-action="Dashboard">Manage Customer</a>
                                    </li>
                                    <li>
                                        <a asp-area="" asp-controller="Customer"
                               asp-action="">View all Customers</a>
                                    </li>
                                </ul>
                            </li>
                        }
                    }


                  

                    <li class="dropdown">
                        <a href="#">Products</a>
                        <ul class="dropdown-content">
                            <li>
                                <a asp-area="" asp-controller="Product"
                               asp-action="Create">Add new products</a>
                            </li>
                            <li>
                                <a asp-area="" asp-controller="Product"
                               asp-action="Dashboard">Manage Product</a>
                            </li>
                            <li>
                                <a asp-area="" asp-controller="Product"
                               asp-action="">View all Products</a>
                            </li>
                        </ul>
                    </li>

                    @* <li><a href="#">Products</a></li> *@
                    <li>
                        <a asp-area="" asp-controller="Transaction"
                       asp-action="">Transactions</a>
                    </li>
                </ul>
            </div>


        }




        <div class="bodycontains">

            <main role="main" class="pb-3">
                @* <div class="bd-line"> *@

                @RenderBody()
                @* </div> *@
            </main>
            @*
            <footer class="border-top footer text-muted">
            <div class="container">
            &copy; 2022 - SMS_MVCDTO - <a asp-area=""
            asp-controller="Home"
            asp-action="Privacy">Privacy</a>
            </div>
            </footer>*@
        </div>



    </div>



    @* <div> *@

    @* <div class="footercontain bd-gline"> *@



    @* </div> *@


    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>

</html>

SMS_MVCDTO33/SMS_MVCDTO/Views/Shared/_Navigation.cshtml
@page
@model SMS_MVCDTO.Views.Shared._Navigation
@{
    ViewData["Title"] = "_Navigation";
}

<h1>@ViewData["Title"]</h1>

<div>
    <nav>
        <ul>
            <li><a href="/home">Home</a></li>
            <li><a href="/about">About</a></li>
            <li><a href="/Services">Services</a></li>
            <li><a href="/contact">Contact</a></li>
        </ul>
    </nav>
</div>