SMS_MVCDTO33/SMS_MVCDTO/Models/Entities/Product.cs
using Microsoft.EntityFrameworkCore;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace SMS_MVCDTO.Models.Entities
{
    //[Index(nameof(Barcode), IsUnique = true)]
    public class Product : BaseEntity
    {
        //public int Id { get; set; }
        //public IList<ProductCategoryProduct> ProductCategoryProducts { get; set; }
        //public IList<ProductCategory> productCategories { get; set; }
        public string ProductCategoryId { get; set; }
        public ProductCategory ProductCategory { get; set; }
        //public int TransactionId { get; set; }
        //public Transaction Transaction { get; set; }
        [Required]
        [Key]
        public string Barcode { get; set; }
        public string Name { get; set; }
        public string Category { get; set; }
        public string Description { get; set; }
        public double SellingPrice { get; set; }
        public double Quantity { get; set; }
        public double ReorderLevel { get; set; }
        public bool IsAvailable { get; set; }

    }
}

SMS_MVCDTO33/SMS_MVCDTO/Controllers/ProductCategoryController.cs
using Microsoft.AspNetCore.Mvc;
using SMS_MVCDTO.Interfaces.Services;
using SMS_MVCDTO.Models.DTOs.ProductCategoriesDTOs;

namespace SMS_MVCDTO.Controllers
{
    public class ProductCategoryController : Controller
    {
        private readonly IProductCategoryService _productCategory;
        public ProductCategoryController(IProductCategoryService productCategory)
        {
            _productCategory = productCategory;
        }

        public IActionResult Index()
        {
            var categories = _productCategory.GetAll();
            return View(categories);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create (CreateProductCategoryRequestModel createProductCategory)
        {
            if (createProductCategory != null)
            {
                var isExit = _productCategory.GetById(createProductCategory.Name);
                if (isExit == null)
                {
                    _productCategory.Create(createProductCategory);
                    TempData["success"] = "Category Created Successfully.";
                    return RedirectToAction("Index");
                }
                TempData["failed"] = "Category already exist.";
                return View();
            }
          
                TempData["failed"] = "Failed. ";
                return View();
           
        }


        public IActionResult Edit (string categoryCode)
        {
            var productCategory = _productCategory.GetById(categoryCode);
            if (productCategory == null)
            {
                return NotFound();
            }
            return View(productCategory);
        }



        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(ProductCategoryResponseModel productCategory)
        {

            _productCategory.Update(productCategory);
            TempData["success"] = "Updated Successfully.";
            return RedirectToAction(nameof(Index));
        }

        public IActionResult Delete (string categoryCode)
        {
            if (categoryCode != null)
            {
                _productCategory.Delete(categoryCode);
                return RedirectToAction(nameof(Index));
            }
            return NotFound();
        }

        public IActionResult DeletePreview (string categoryCode)
        {
            if (categoryCode != null)
            {
                var productCategory = _productCategory.GetById(categoryCode);

                if (productCategory != null)
                {
                    return View(productCategory);
                }
                return NotFound();
            }
            return NotFound();
        }
    }
}

SMS_MVCDTO33/SMS_MVCDTO/Controllers/ProductController.cs
using Microsoft.AspNetCore.Mvc;
using SMS_MVCDTO.Interfaces.Services;
using SMS_MVCDTO.Models.ViewModels;

namespace SMS_MVCDTO.Controllers
{
    public class ProductController : Controller
    {
        private readonly IProductService _product;
        private readonly IProductCategoryService _category;
        public ProductController(IProductService product, IProductCategoryService category)
        {
            _product = product;
            _category = category;
        }

        public IActionResult Index()
        {
            var product = _product.GetAll();
            return View(product);
        }

        public IActionResult BelowReorderLevel()
        {
            var product = _product.BelowReorderLevel();
            return View(product);
        }

        public IActionResult Dashboard()
        {
            var product = _product.GetAll();
            return View(product);
        }

        public IActionResult Create()
        {
            var categories = _category.GetAll().ToList();
            var viewModel = new NewProductViewModel
            {
                PCategory = categories
            };
            return View(viewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(NewProductViewModel product)
        {

            if (product != null)
            {
                var existByName = _product.GetById(product.CreateProduct.Barcode);
                if (existByName == null)
                {
                    _product.Create(product.CreateProduct);
                    TempData["success"] = "Created Successfully.";
                    //return RedirectToAction("Index");
                    return RedirectToAction("Dashboard", "Attendant");
                }
                TempData["failed"] = "already exist.";
                return View();
            }

            TempData["failed"] = "failed.";
            return View(product);

        }

        public IActionResult Edit(string barCode)
        {

            var product = _product.GetById(barCode);
            if (product == null)
            {
                return NotFound();
            }
            var categories = _category.GetAll().ToList();
            var viewModel = new NewProductViewModel
            {
                UpdateProduct = product,
                PCategory = categories,
            };
            return View(viewModel);

        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(NewProductViewModel product)
        {
            if (product != null)
            {
                _product.Update(product.UpdateProduct);
                TempData["success"] = "product updated Successfully.";
                return RedirectToAction(nameof(Index));
            }
            TempData["failed"] = "failed.";
            return View(product);
        }


        public IActionResult DeletePreview(string barCode)
        {
            if (barCode != null)
            {
                var product = _product.GetById(barCode);
                if (product != null)
                {
                    return View(product);
                }
                return NotFound();
            }

            return NotFound();
        }

        public IActionResult Delete(string barCode)
        {
            if (barCode != null)
            {
                _product.Delete(barCode);
                return RedirectToAction(nameof(Index));
            }
            return NotFound();
        }

        public IActionResult Details(string barCode)
        {
            if (barCode != null)
            {
                var product = _product.GetById(barCode);
                if (product != null)
                {
                    return View(product);
                }
                return NotFound();
            }
            return NotFound();
        }

        public IActionResult GetById(string barCode)
        {
            if (barCode != null)
            {
                var product = _product.GetById(barCode);
                if (product != null)
                {
                    return View(product);
                }
                return NotFound();
            }
            return NotFound();
        }

        public IActionResult GetByName(string name)
        {
            if (name != null)
            {
                var product = _product.GetByName(name);
                if (product != null)
                {
                    return View(product);
                }
                return NotFound();
            }
            return NotFound();
        }
    }
}

SMS_MVCDTO33/SMS_MVCDTO/Controllers/TransactionController.cs
using Microsoft.AspNetCore.Mvc;
using SMS_MVCDTO.Interfaces.Services;
using SMS_MVCDTO.Models.DTOs.TransactionDTOs;
using SMS_MVCDTO.Models.ViewModels;

namespace SMS_MVCDTO.Controllers
{
    public class TransactionController : Controller
    {
        private readonly ITransactionService _transaction;
        private readonly IProductService _product;
        public TransactionController(ITransactionService transaction, IProductService product)
        {
            _transaction = transaction;
            _product = product;
        }

        public IActionResult Index(int id)
        {
            if (id != 0)
            {
                var transactions = _transaction.GetAll();
                return View(transactions);
            }
            else
            {
                var transactions = _transaction.GetAllOrderByDate();
                return View(transactions);
            }

        }


        public IActionResult Dashboard()
        {
            var transactions = _transaction.GetAll();
            return View(transactions);
        }


        public IActionResult Create(string barCode)
        {
            var product = _product.GetById(barCode);

            if (product == null)
            {
                return NotFound();
            }

            var productTransact = new CreateProductTransactionViewModel
            {
                Product = product,

            };

            return View(productTransact);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(CreateProductTransactionViewModel productTransaction)
        {

            var transaction = productTransaction.Transaction;

            if (transaction != null)
            {
                transaction.BarCode = productTransaction.Product.Data.Barcode;
                _transaction.Create(transaction);
                TempData["success"] = "Created Successfully.";
                return RedirectToAction("Index");
            }
            TempData["failed"] = "failed.";
            return View();
        }

        public IActionResult DeletePreview(string referenceNo)
        {
            if (referenceNo != null)
            {
                var transaction = _transaction.GetById(referenceNo);
                if (transaction != null)
                {
                    return View(transaction);
                }
                return NotFound();
            }

            return NotFound();
        }

        public IActionResult Delete(string referenceNo)
        {
            if (referenceNo != null)
            {
                _transaction.Delete(referenceNo);
                return RedirectToAction(nameof(Index));
            }
            return NotFound();
        }

        public IActionResult Details(string referenceNo)
        {
            if (referenceNo != null)
            {
                var transaction = _transaction.GetById(referenceNo);
                if (transaction != null)
                {
                    return View(transaction);
                }
                return NotFound();
            }
            return NotFound();
        }

        public IActionResult GetByName(string name)
        {
            if (name != null)
            {
                var transaction = _transaction.GetTransactionByCustomerName(name);
                if (transaction != null)
                {
                    return View(transaction);
                }
                return NotFound();
            }
            return NotFound();
        }

        public IActionResult GetByAttendant(string staffId)
        {
            if (staffId != null)
            {
                var transaction = _transaction.GetByStaffId(staffId);
                if (transaction != null)
                {
                    return View(transaction);
                }
                return NotFound();
            }
            return NotFound();
        }
    }


}

SMS_MVCDTO33/SMS_MVCDTO/Views/Product/Create.cshtml
@model SMS_MVCDTO.Models.ViewModels.NewProductViewModel


@{
    ViewData["Title"] = "Create";
}
@{
    if (TempData["success"] != null)
    {
        <h2>@TempData["success"]</h2>
    }
    if (TempData["failed"] != null)
    {
        <h2>@TempData["failed"]</h2>
    }
}


<main class="main">
    <!-- <div class="dashboard"> -->
    <div class="form-container">

        <div id="Data-form">
            @using (Html.BeginForm("Create", "Product"))
            {

                <h1>Add new Product</h1>

                <hr />
                <div class="form-group">
                    @Html.LabelFor(x => x.CreateProduct.Barcode, new {@class = "control-label"})
                    @Html.TextBoxFor(x => x.CreateProduct.Barcode, new {@class = "form-control"})
                    @Html.ValidationMessageFor(x => x.CreateProduct.Barcode,"", new {@class="text-danger"})
                </div>

                <div class="form-group">
                    @Html.LabelFor(x => x.CreateProduct.Name, new {@class = "control-label"})
                    @Html.TextBoxFor(x => x.CreateProduct.Name, new {@class = "form-control"})
                    @Html.ValidationMessageFor(x => x.CreateProduct.Name,"", new {@class="text-danger"})
                </div>

                <div class="form-group">
                    @Html.LabelFor(x => x.CreateProduct.Description, new {@class = "control-label"})
                    @Html.TextBoxFor(x => x.CreateProduct.Description, new {@class = "form-control"})
                    @Html.ValidationMessageFor(x => x.CreateProduct.Description,"", new {@class="text-danger"})
                </div>

                <div class="form-group">
                    @Html.LabelFor(x => x.CreateProduct.SellingPrice, new {@class = "control-label"})
                    @Html.TextBoxFor(x => x.CreateProduct.SellingPrice, new {@class = "form-control"})
                    @Html.ValidationMessageFor(x => x.CreateProduct.SellingPrice,"", new {@class="text-danger"})
                </div>

                <div class="form-group">
                    @Html.LabelFor(x => x.CreateProduct.Quantity, new {@class = "control-label"})
                    @Html.TextBoxFor(x => x.CreateProduct.Quantity, new {@class = "form-control"})
                    @Html.ValidationMessageFor(x => x.CreateProduct.Quantity,"", new {@class="text-danger"})
                </div>

                <div class="form-group">
                    @Html.LabelFor(x => x.CreateProduct.ReorderLevel, new {@class = "control-label"})
                    @Html.TextBoxFor(x => x.CreateProduct.ReorderLevel, new {@class = "form-control"})
                    @Html.ValidationMessageFor(x => x.CreateProduct.ReorderLevel,"", new {@class="text-danger"})
                </div>

                <div class="form-group">
                    @Html.LabelFor(x => x.PCategory, new {@class = "control-label"})
                    @Html.DropDownListFor(x => x.CreateProduct.Category, new SelectList(Model.PCategory,"Data.CategoryCode","Data.Name"),"Select Category" ,new {@class = "form-control"})
                    @Html.ValidationMessageFor(x => x.CreateProduct.Category,"", new {@class="text-danger"})
                </div>

                <div class="form-group">
                    <button type="submit" class="btn btn-success">Add</button>
                </div>
            }

        </div>

    </div>

    <!-- search box  -->
    <div class="search-container">
        <form>
            <input type="text" placeholder="Search...">
            <button type="submit"><i class="fa fa-search"></i> Search </button>
        </form>
    </div>



    @section Scripts {
        @{
            await Html.RenderPartialAsync("_ValidationScriptsPartial");
        }
    }

</main>
@* ends here *@

SMS_MVCDTO33/SMS_MVCDTO/Views/Product/Dashboard.cshtml
@model IEnumerable<SMS_MVCDTO.Models.DTOs.ProductDTOs.ProductResponseModel>

@{
    ViewData["Title"] = "Dashboard";
}

@{
    if (TempData["Success"] != null)
    {
        <h2>@TempData["success"]</h2>
    }
    if (TempData["failed"] != null)
    {
        <h2>@TempData["failed"]</h2>
    }
}


<h1>Manage Product</h1>


<div class="container1">
    <div class="box box0">
        <form >

        </form>
    </div>
    <div class="box box2">
        <form asp-controller="Product" asp-action="GetByName">
            <input type="text" placeholder="Search by Name.." name="name">
            <button type="submit">Search</button>
        </form>
    </div>

    <div class="box box3">
        <form  asp-action="GetById">
            <input type="search" placeholder="Barcode.." aria-label="Search" name="barCode">
            <button type="submit">Search</button>
        </form>
    </div>

    @*<div class="box box3">
        <form asp-controller="Product" asp-action="GetByName">
            <input type="text" placeholder="Search by Email.." name="email">
            <button type="submit">Search</button>
        </form>
    </div>*@

</div>



<div class="container">

    <div class="box box1"> side bar </div>
</div>


<p>
    <button class="btn btn-outline-info"> <a asp-action="Create">Add Product</a></button> || <button class="btn btn-outline-warning"> <a asp-controller="ProductCategory" asp-action="Create">Add New Category</a></button>
</p>

<table class="table table-info col-md-4">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Data.Barcode)
            </th>

            <th>
                @Html.DisplayNameFor(model => model.Data.Name)
            </th>

            <th>
                @Html.DisplayNameFor(model => model.Data.Quantity)
            </th>

            <th>
                @Html.DisplayNameFor(model => model.Data.SellingPrice)
            </th>

            <th></th>
        </tr>
    </thead>
    <tbody>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Data.Barcode)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Data.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Data.Quantity)
                </td>

                <td>
                    @Html.DisplayFor(modelItem => item.Data.SellingPrice)
                </td>

                <td>
                    @*<a asp-action="Edit" asp-route-Barcode="@item.Data.Barcode">Edit</a> |*@
                    <a asp-action="Details" asp-route-Barcode="@item.Data.Barcode">Details</a> |
                    @*<a asp-action="DeletePreview" asp-route-Barcode="@item.Data.Barcode">Delete</a> |*@
                    <a asp-controller="Transaction" asp-action="Create" asp-route-Barcode="@item.Data.Barcode">Buy</a>
                </td>
            </tr>
        }
    </tbody>
</table>

SMS_MVCDTO33/SMS_MVCDTO/Views/Product/Delete.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

SMS_MVCDTO33/SMS_MVCDTO/Views/Product/Edit.cshtml
@model SMS_MVCDTO.Models.ViewModels.NewProductViewModel

@{
    ViewData["Title"] = "Edit";
}
@{
    if (TempData["success"] != null)
    {
        <h2>@TempData["success"]</h2>
    }
    if (TempData["failed"] != null)
    {
        <h2>@TempData["failed"]</h2>
    }
}

<h1> Update Product details</h1>
<hr />
    

<div class="col-md-4">
    @using (Html.BeginForm("Edit", "Product"))
    {

        <div class="form-group">
            @Html.HiddenFor(x => x.UpdateProduct.Data.Barcode, new {@class = "form-control"})
        </div>

        <div class="form-group">
            @Html.LabelFor(x => x.UpdateProduct.Data.Name, new {@class = "control-label"})
            @Html.TextBoxFor(x => x.UpdateProduct.Data.Name, new {@class = "form-control"})
            @Html.ValidationMessageFor(x => x.UpdateProduct.Data.Name,"", new {@class="text-danger"})
        </div>

        <div class="form-group">
            @Html.LabelFor(x => x.UpdateProduct.Data.Description, new {@class = "control-label"})
            @Html.TextBoxFor(x => x.UpdateProduct.Data.Description, new {@class = "form-control"})
            @Html.ValidationMessageFor(x => x.UpdateProduct.Data.Description,"", new {@class="text-danger"})
        </div>

        <div class="form-group">
            @Html.LabelFor(x => x.UpdateProduct.Data.SellingPrice, new {@class = "control-label"})
            @Html.TextBoxFor(x => x.UpdateProduct.Data.SellingPrice, new {@class = "form-control"})
            @Html.ValidationMessageFor(x => x.UpdateProduct.Data.SellingPrice,"", new {@class="text-danger"})
        </div>

        <div class="form-group">
            @Html.LabelFor(x => x.UpdateProduct.Data.Quantity, new {@class = "control-label"})
            @Html.TextBoxFor(x => x.UpdateProduct.Data.Quantity, new {@class = "form-control"})
            @Html.ValidationMessageFor(x => x.UpdateProduct.Data.Quantity,"", new {@class="text-danger"})
        </div>

        <div class="form-group">
            @Html.LabelFor(x => x.UpdateProduct.Data.ReorderLevel, new {@class = "control-label"})
            @Html.TextBoxFor(x => x.UpdateProduct.Data.ReorderLevel, new {@class = "form-control"})
            @Html.ValidationMessageFor(x => x.UpdateProduct.Data.ReorderLevel,"", new {@class="text-danger"})
        </div>

        <div>
            @Html.LabelFor(x => x.PCategory, new {@class = "control-label"})
            @Html.DropDownListFor(x => x.UpdateProduct.Data.Category, new SelectList(Model.PCategory,"Data.CategoryCode","Data.Name"),"Select Category" ,new {@class = "form-control"})
            @Html.ValidationMessageFor(x => x.UpdateProduct.Data.Category,"", new {@class="text-danger"})

        </div>

        <div class="form-group">
            <button type="submit" class="btn btn-success">Add</button>
        </div>
    }
</div>
@section scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

SMS_MVCDTO33/SMS_MVCDTO/Views/Product/GetById.cshtml
@model SMS_MVCDTO.Models.DTOs.ProductDTOs.ProductResponseModel


@{
    ViewData["Title"] = "Details";
}

@{
    if (TempData["Success"] != null)
    {
        <h2>@TempData["success"]</h2>
    }
    if (TempData["failed"] != null)
    {
        <h2>@TempData["failed"]</h2>
    }
}








<main class="main">
    <!-- <div class="dashboard"> -->
    <div class="form-container">

@*        <div id="Data-form">


*@




            <table class="table table-info col-md-4">
                <thead>
                    <tr>
                        <th>
                            @Html.DisplayNameFor(model => model.Data.Barcode)
                        </th>

                        <th>
                            @Html.DisplayNameFor(model => model.Data.Name)
                        </th>

                        <th>
                            @Html.DisplayNameFor(model => model.Data.Quantity)
                        </th>

                        <th>
                            @Html.DisplayNameFor(model => model.Data.SellingPrice)
                        </th>

                        <th></th>
                    </tr>
                </thead>

                <tbody>
                <tr>
                            <td>
                            @Html.DisplayFor(modelItem => modelItem.Data.Barcode)
                            </td>
                            <td>
                            @Html.DisplayFor(modelItem => modelItem.Data.Name)
                            </td>
                            <td>
                            @Html.DisplayFor(modelItem => modelItem.Data.Quantity)
                            </td>

                            <td>
                            @Html.DisplayFor(modelItem => modelItem.Data.SellingPrice)
                            </td>

                            <td>
                                @*<a asp-action="Edit" asp-route-Barcode="@item.Data.Barcode">Edit</a> |*@
                            <a asp-action="Details" asp-route-Barcode="@Model.Data.Barcode">Details</a> |
                                @*<a asp-action="DeletePreview" asp-route-Barcode="@item.Data.Barcode">Delete</a> |*@
                            <a asp-controller="Transaction" asp-action="Create" asp-route-Barcode="@Model.Data.Barcode">Buy</a>
                            </td>
                        </tr>
                    
                </tbody>
            </table>






            
            @{
                /*

            <div class="container1">
                <div>
                    <form asp-action="Edit">
                        <h1>Modify @Model.Data.Name </h1>

                        <div class="form-group">
                            <label asp-for="Data.Barcode" class="control-label"></label>
                            <input asp-for="Data.Barcode" readonly class="form-control" />
                        </div>

                        <div class="form-group">
                            <label asp-for="Data.Name" class="control-label"></label>
                            <input asp-for="Data.Name" readonly class="form-control" />
                        </div>

                        <div class="form-group">
                            <label asp-for="Data.Category" class="control-label"></label>
                            <input asp-for="Data.Category" readonly class="form-control" />
                        </div>

                        <div class="form-group">
                            <label asp-for="Data.Quantity" class="control-label"></label>
                            <input asp-for="Data.Quantity" readonly class="form-control" />
                        </div>


                        <div class="form-group">
                            <label asp-for="Data.SellingPrice" class="control-label"></label>
                            <input asp-for="Data.SellingPrice" readonly class="form-control" />

                        </div>
                        @*
                        <div class="form-group">
                        <input type="submit" value="Save" class="btn btn-success" />
                        </div>*@

                        <div>
                            <a asp-action="Edit" asp-route-barcode="@Model.Data.Barcode" class="btn btn-success">Edit</a> |
                            <a asp-action="Index" class="btn btn-warning">Back to List</a>
                            <input type="submit" value="Save" class="btn btn-success" />
                        </div>
                    </form>
                </div>

            </div>

                 * 
                 */
            }




@*

        </div>
*@
    </div>

    <!-- search box  -->
    <div class="search-container">
        <form>
            <input type="text" placeholder="Search...">
            <button type="submit"><i class="fa fa-search"></i> Search </button>
        </form>
    </div>


    @section Scripts {
        @{
            await Html.RenderPartialAsync("_ValidationScriptsPartial");
        }
    }
</main>
@* ends here *@

SMS_MVCDTO33/SMS_MVCDTO/Views/Product/GetByName.cshtml
@model IEnumerable<SMS_MVCDTO.Models.DTOs.ProductDTOs.ProductResponseModel>

@{
    ViewData["Title"] = "Search result";
}

@{
    if (TempData["Success"] != null)
    {
        <h2>@TempData["success"]</h2>
    }
    if (TempData["failed"] != null)
    {
        <h2>@TempData["failed"]</h2>
    }
}


<h1>Manage Product</h1>


<div class="container1">
    <div class="box box0">
        <form>
        </form>
    </div>
    <div class="box box2">
        <form asp-controller="Product" asp-action="GetByName">
            <input type="text" placeholder="Search by Name.." name="name">
            <button type="submit">Search</button>
        </form>
    </div>

    <div class="box box3">
        <form asp-controller="Product" asp-action="GetById">
            <input type="search" placeholder="Search by barcode.." aria-label="Search" name="barcode">
            <button type="submit">Search</button>
        </form>
    </div>


</div>



<div class="container">

    <div class="box box1"> side bar </div>
</div>


<p>
    <button class="btn btn-outline-info"> <a asp-action="Create">Add Product</a></button> || <button class="btn btn-outline-warning"> <a asp-controller="ProductCategory" asp-action="Create">Add New Category</a></button>
</p>

<table class="table table-info col-md-4">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Data.Barcode)
            </th>

            <th>
                @Html.DisplayNameFor(model => model.Data.Name)
            </th>

            <th>
                @Html.DisplayNameFor(model => model.Data.Quantity)
            </th>

            <th>
                @Html.DisplayNameFor(model => model.Data.SellingPrice)
            </th>

            <th></th>
        </tr>
    </thead>
    <tbody>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Data.Barcode)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Data.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Data.Quantity)
                </td>

                <td>
                    @Html.DisplayFor(modelItem => item.Data.SellingPrice)
                </td>

                <td>
                    <a asp-action="Details" asp-route-Barcode="@item.Data.Barcode">Details</a> ||
                    <a asp-controller="Transaction" asp-action="Create" asp-route-Barcode="@item.Data.Barcode">Buy</a>
                </td>
            </tr>
        }
    </tbody>
</table>